
services:
  db:
    container_name: my-postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/data/postgres
    networks:
      - db
    restart: unless-stopped

  customer-api:
    container_name: customer-api
    image: idockerwas/customer-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "9090:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
#    command:
#      - --spring.datasource.url=jdbc:postgresql://db:5432/customer


volumes:
  db_data:
networks:
  db:
    driver: bridge
