server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/customer
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false


